// <auto-generated />
using System;
using Gov.Import.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gov.Import.Migrations
{
    [DbContext(typeof(EntityContext))]
    partial class EntityContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gov.Import.Data.FapData", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AttachmentDocumentDate")
                        .HasColumnType("text");

                    b.Property<string>("AttachmentFileName")
                        .HasColumnType("text");

                    b.Property<string>("AttachmentFileSize")
                        .HasColumnType("text");

                    b.Property<string>("AttachmentPublishDate")
                        .HasColumnType("text");

                    b.Property<string>("AttachmentUrl")
                        .HasColumnType("text");

                    b.Property<float?>("ExpensepaymentFirstPlanYearFz223Sum")
                        .HasColumnType("real");

                    b.Property<float?>("ExpensepaymentFirstPlanYearFz44Sum")
                        .HasColumnType("real");

                    b.Property<float?>("ExpensepaymentFirstPlanYearTotalSum")
                        .HasColumnType("real");

                    b.Property<string>("ExpensepaymentLineCode")
                        .HasColumnType("text");

                    b.Property<string>("ExpensepaymentName")
                        .HasColumnType("text");

                    b.Property<float?>("ExpensepaymentNextYearFz223Sum")
                        .HasColumnType("real");

                    b.Property<float?>("ExpensepaymentNextYearFz44Sum")
                        .HasColumnType("real");

                    b.Property<float?>("ExpensepaymentNextYearTotalSum")
                        .HasColumnType("real");

                    b.Property<float?>("ExpensepaymentSecondPlanYearFz223Sum")
                        .HasColumnType("real");

                    b.Property<float?>("ExpensepaymentSecondPlanYearFz44Sum")
                        .HasColumnType("real");

                    b.Property<float?>("ExpensepaymentSecondPlanYearTotalSum")
                        .HasColumnType("real");

                    b.Property<int?>("ExpensepaymentYear")
                        .HasColumnType("integer");

                    b.Property<float?>("PlanpaymentCapitalInvestment")
                        .HasColumnType("real");

                    b.Property<float?>("PlanpaymentFinancialInsurance")
                        .HasColumnType("real");

                    b.Property<float?>("PlanpaymentFinancialProvision")
                        .HasColumnType("real");

                    b.Property<float?>("PlanpaymentHealthInsurance")
                        .HasColumnType("real");

                    b.Property<string>("PlanpaymentKbk")
                        .HasColumnType("text");

                    b.Property<string>("PlanpaymentLineCode")
                        .HasColumnType("text");

                    b.Property<float?>("PlanpaymentMainCapitalInvestment")
                        .HasColumnType("real");

                    b.Property<float?>("PlanpaymentMainFinancialInsurance")
                        .HasColumnType("real");

                    b.Property<float?>("PlanpaymentMainFinancialProvision")
                        .HasColumnType("real");

                    b.Property<float?>("PlanpaymentMainHealthInsurance")
                        .HasColumnType("real");

                    b.Property<string>("PlanpaymentMainKbk")
                        .HasColumnType("text");

                    b.Property<string>("PlanpaymentMainLineCode")
                        .HasColumnType("text");

                    b.Property<string>("PlanpaymentMainName")
                        .HasColumnType("text");

                    b.Property<float?>("PlanpaymentMainProvision781")
                        .HasColumnType("real");

                    b.Property<float?>("PlanpaymentMainServiceGrant")
                        .HasColumnType("real");

                    b.Property<float?>("PlanpaymentMainServiceTotal")
                        .HasColumnType("real");

                    b.Property<float?>("PlanpaymentMainTotal")
                        .HasColumnType("real");

                    b.Property<string>("PlanpaymentName")
                        .HasColumnType("text");

                    b.Property<float?>("PlanpaymentProvision781")
                        .HasColumnType("real");

                    b.Property<float?>("PlanpaymentServiceGrant")
                        .HasColumnType("real");

                    b.Property<float?>("PlanpaymentServiceTotal")
                        .HasColumnType("real");

                    b.Property<float?>("PlanpaymentTotal")
                        .HasColumnType("real");

                    b.Property<string>("ReferenceLineCode")
                        .HasColumnType("text");

                    b.Property<string>("ReferenceName")
                        .HasColumnType("text");

                    b.Property<float?>("ReferenceTotal")
                        .HasColumnType("real");

                    b.Property<string>("TemporaryresourceLineCode")
                        .HasColumnType("text");

                    b.Property<string>("TemporaryresourceName")
                        .HasColumnType("text");

                    b.Property<float?>("TemporaryresourceTotal")
                        .HasColumnType("real");

                    b.Property<float?>("accountsCash")
                        .HasColumnType("real");

                    b.Property<float?>("cash")
                        .HasColumnType("real");

                    b.Property<string>("clientRegionCode")
                        .HasColumnType("text");

                    b.Property<string>("clientRegionName")
                        .HasColumnType("text");

                    b.Property<string>("date")
                        .HasColumnType("text");

                    b.Property<string>("dateApprovel")
                        .HasColumnType("text");

                    b.Property<float?>("debentures")
                        .HasColumnType("real");

                    b.Property<float?>("depositCash")
                        .HasColumnType("real");

                    b.Property<string>("financialYear")
                        .HasColumnType("text");

                    b.Property<bool>("first")
                        .HasColumnType("boolean");

                    b.Property<string>("firstYearPeriod")
                        .HasColumnType("text");

                    b.Property<string>("founder")
                        .HasColumnType("text");

                    b.Property<string>("founderAgencyId")
                        .HasColumnType("text");

                    b.Property<string>("founderGlavaCode")
                        .HasColumnType("text");

                    b.Property<string>("fullClientName")
                        .HasColumnType("text");

                    b.Property<string>("inn")
                        .HasColumnType("text");

                    b.Property<bool>("isArchive")
                        .HasColumnType("boolean");

                    b.Property<string>("kpp")
                        .HasColumnType("text");

                    b.Property<float?>("kredit")
                        .HasColumnType("real");

                    b.Property<bool>("last")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("lastUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("number")
                        .HasColumnType("integer");

                    b.Property<int>("numberOfElements")
                        .HasColumnType("integer");

                    b.Property<string>("okeiCode")
                        .HasColumnType("text");

                    b.Property<string>("okeiSymbol")
                        .HasColumnType("text");

                    b.Property<string>("orgType")
                        .HasColumnType("text");

                    b.Property<float?>("others")
                        .HasColumnType("real");

                    b.Property<string>("secondYearPeriod")
                        .HasColumnType("text");

                    b.Property<int>("size")
                        .HasColumnType("integer");

                    b.Property<string>("sort")
                        .HasColumnType("text");

                    b.Property<float?>("sumBalanceNoFinancial")
                        .HasColumnType("real");

                    b.Property<float?>("sumDelayedPayable")
                        .HasColumnType("real");

                    b.Property<float?>("sumDepthExpenses")
                        .HasColumnType("real");

                    b.Property<float?>("sumDepthIncome")
                        .HasColumnType("real");

                    b.Property<float?>("sumFinancialActives")
                        .HasColumnType("real");

                    b.Property<float?>("sumObligations")
                        .HasColumnType("real");

                    b.Property<float?>("sumRealEstate")
                        .HasColumnType("real");

                    b.Property<float?>("sumRealEstateResidual")
                        .HasColumnType("real");

                    b.Property<float?>("sumValuableProperty")
                        .HasColumnType("real");

                    b.Property<float?>("sumValuablePropertyResidual")
                        .HasColumnType("real");

                    b.Property<string>("summaryRegistryCode")
                        .HasColumnType("text");

                    b.Property<int>("totalElements")
                        .HasColumnType("integer");

                    b.Property<int>("totalElementsInteger")
                        .HasColumnType("integer");

                    b.Property<int>("totalPages")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("Faps");
                });
#pragma warning restore 612, 618
        }
    }
}
